# Site
name: "AVS Blog"
title: "AVS Blog"
description: "Azure VMware Solution (AVS) Community Blog"
baseurl: https://avs.ms
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  tredavis:
    name: "Trevor Davis"
    display_name: "Trevor Davis"
  carlosv:
    name: "Carlos Villuendas"
    display_name: "Carlos Villuendas"
  scholden:
    name: "Scott Holden"
    display_name: "Scott Holden"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'

# Other collections
collections:
  news_headlines:
    hidden: true
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
